# -*- coding: utf-8 -*-
"""366LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zW7ejPXwS01nBS9WOTdGkfGzdzBtt7X
"""

from google.colab import drive
drive.mount('/content/drive')

import random
def read_student_ids(filename):
    try:
        with open(filename, 'r') as file:
            student_ids = [line.strip() for line in file if line.strip()]
        return student_ids
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
        return []

filename = '/content/drive/MyDrive/CSE366_LAB1/ids.txt'
print(read_student_ids(filename))

def conduct_viva(student_ids):
    unselected_students = student_ids[:]  # Copy for unselected students
    viva_count = 1

    while unselected_students:
        selected_student = random.choice(unselected_students)
        print(f"Viva #{viva_count}: {selected_student}")
        unselected_students.remove(selected_student)
        viva_count += 1

    print("\nAll students have been selected for the viva.")

student_ids = read_student_ids(filename)

if student_ids:
  conduct_viva(student_ids)
  print("\nResetting the list for another round.")
  # restored list
  print("Restored List:", student_ids)